version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-db-borrow-service
    environment:
      POSTGRES_DB: borrow_service_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5434:5432"
    volumes:
      - pgdata_borrow:/var/lib/postgresql/data

volumes:
  pgdata_borrow:

