version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-db-user-service
    environment:
      POSTGRES_DB: user_service_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5435:5432"
    volumes:
      - pgdata_user:/var/lib/postgresql/data

volumes:
  pgdata_user:

